// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// glam_myhfunc1
NumericVector glam_myhfunc1(NumericMatrix x, double y);
RcppExport SEXP _glam3_glam_myhfunc1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myhfunc1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_myhfunc2
NumericVector glam_myhfunc2(NumericMatrix x, double y);
RcppExport SEXP _glam3_glam_myhfunc2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myhfunc2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_myhfunc3
NumericVector glam_myhfunc3(NumericMatrix x, double y);
RcppExport SEXP _glam3_glam_myhfunc3(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myhfunc3(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_myslopefunc
NumericVector glam_myslopefunc(NumericMatrix x);
RcppExport SEXP _glam3_glam_myslopefunc(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myslopefunc(x));
    return rcpp_result_gen;
END_RCPP
}
// glam_mydiff1
NumericVector glam_mydiff1(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _glam3_glam_mydiff1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_mydiff1(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_mydiff2
NumericVector glam_mydiff2(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _glam3_glam_mydiff2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_mydiff2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_mydiff3
NumericVector glam_mydiff3(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _glam3_glam_mydiff3(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_mydiff3(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_myfunc4
NumericVector glam_myfunc4(NumericMatrix x);
RcppExport SEXP _glam3_glam_myfunc4(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myfunc4(x));
    return rcpp_result_gen;
END_RCPP
}
// glam_myfunc5
NumericVector glam_myfunc5(NumericMatrix x, double y);
RcppExport SEXP _glam3_glam_myfunc5(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myfunc5(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_myfunc6
NumericVector glam_myfunc6(NumericMatrix x, double y);
RcppExport SEXP _glam3_glam_myfunc6(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(glam_myfunc6(x, y));
    return rcpp_result_gen;
END_RCPP
}
// glam_scorefunctheta3
NumericVector glam_scorefunctheta3(NumericMatrix x, double theta, double mu, double s);
RcppExport SEXP _glam3_glam_scorefunctheta3(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_scorefunctheta3(x, theta, mu, s));
    return rcpp_result_gen;
END_RCPP
}
// glam_scorefuncmu3
NumericVector glam_scorefuncmu3(NumericMatrix x, double theta, double mu, double s);
RcppExport SEXP _glam3_glam_scorefuncmu3(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_scorefuncmu3(x, theta, mu, s));
    return rcpp_result_gen;
END_RCPP
}
// glam_scorefunctheta2
NumericVector glam_scorefunctheta2(NumericMatrix x, double theta, double mu, double s);
RcppExport SEXP _glam3_glam_scorefunctheta2(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_scorefunctheta2(x, theta, mu, s));
    return rcpp_result_gen;
END_RCPP
}
// glam_scorefuncmu2
NumericVector glam_scorefuncmu2(NumericMatrix x, double theta, double mu, double s);
RcppExport SEXP _glam3_glam_scorefuncmu2(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_scorefuncmu2(x, theta, mu, s));
    return rcpp_result_gen;
END_RCPP
}
// glam_scorefunctheta1
NumericVector glam_scorefunctheta1(NumericMatrix x, double theta, double mu, double s);
RcppExport SEXP _glam3_glam_scorefunctheta1(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_scorefunctheta1(x, theta, mu, s));
    return rcpp_result_gen;
END_RCPP
}
// glam_scorefuncmu1
NumericVector glam_scorefuncmu1(NumericMatrix x, double theta, double mu, double s);
RcppExport SEXP _glam3_glam_scorefuncmu1(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(glam_scorefuncmu1(x, theta, mu, s));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _glam3_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glam3_glam_myhfunc1", (DL_FUNC) &_glam3_glam_myhfunc1, 2},
    {"_glam3_glam_myhfunc2", (DL_FUNC) &_glam3_glam_myhfunc2, 2},
    {"_glam3_glam_myhfunc3", (DL_FUNC) &_glam3_glam_myhfunc3, 2},
    {"_glam3_glam_myslopefunc", (DL_FUNC) &_glam3_glam_myslopefunc, 1},
    {"_glam3_glam_mydiff1", (DL_FUNC) &_glam3_glam_mydiff1, 2},
    {"_glam3_glam_mydiff2", (DL_FUNC) &_glam3_glam_mydiff2, 2},
    {"_glam3_glam_mydiff3", (DL_FUNC) &_glam3_glam_mydiff3, 2},
    {"_glam3_glam_myfunc4", (DL_FUNC) &_glam3_glam_myfunc4, 1},
    {"_glam3_glam_myfunc5", (DL_FUNC) &_glam3_glam_myfunc5, 2},
    {"_glam3_glam_myfunc6", (DL_FUNC) &_glam3_glam_myfunc6, 2},
    {"_glam3_glam_scorefunctheta3", (DL_FUNC) &_glam3_glam_scorefunctheta3, 4},
    {"_glam3_glam_scorefuncmu3", (DL_FUNC) &_glam3_glam_scorefuncmu3, 4},
    {"_glam3_glam_scorefunctheta2", (DL_FUNC) &_glam3_glam_scorefunctheta2, 4},
    {"_glam3_glam_scorefuncmu2", (DL_FUNC) &_glam3_glam_scorefuncmu2, 4},
    {"_glam3_glam_scorefunctheta1", (DL_FUNC) &_glam3_glam_scorefunctheta1, 4},
    {"_glam3_glam_scorefuncmu1", (DL_FUNC) &_glam3_glam_scorefuncmu1, 4},
    {"_glam3_rcpp_hello_world", (DL_FUNC) &_glam3_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_glam3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
