# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glam_myhfunc1 <- function(x, y) {
    .Call(`_glam3_glam_myhfunc1`, x, y)
}

glam_myhfunc2 <- function(x, y) {
    .Call(`_glam3_glam_myhfunc2`, x, y)
}

glam_myhfunc3 <- function(x, y) {
    .Call(`_glam3_glam_myhfunc3`, x, y)
}

glam_myslopefunc <- function(x) {
    .Call(`_glam3_glam_myslopefunc`, x)
}

glam_mydiff1 <- function(x, y) {
    .Call(`_glam3_glam_mydiff1`, x, y)
}

glam_mydiff2 <- function(x, y) {
    .Call(`_glam3_glam_mydiff2`, x, y)
}

glam_mydiff3 <- function(x, y) {
    .Call(`_glam3_glam_mydiff3`, x, y)
}

glam_myfunc4 <- function(x) {
    .Call(`_glam3_glam_myfunc4`, x)
}

glam_myfunc5 <- function(x, y) {
    .Call(`_glam3_glam_myfunc5`, x, y)
}

glam_myfunc6 <- function(x, y) {
    .Call(`_glam3_glam_myfunc6`, x, y)
}

glam_scorefunctheta3 <- function(x, theta, mu, s) {
    .Call(`_glam3_glam_scorefunctheta3`, x, theta, mu, s)
}

glam_scorefuncmu3 <- function(x, theta, mu, s) {
    .Call(`_glam3_glam_scorefuncmu3`, x, theta, mu, s)
}

glam_scorefunctheta2 <- function(x, theta, mu, s) {
    .Call(`_glam3_glam_scorefunctheta2`, x, theta, mu, s)
}

glam_scorefuncmu2 <- function(x, theta, mu, s) {
    .Call(`_glam3_glam_scorefuncmu2`, x, theta, mu, s)
}

glam_scorefunctheta1 <- function(x, theta, mu, s) {
    .Call(`_glam3_glam_scorefunctheta1`, x, theta, mu, s)
}

glam_scorefuncmu1 <- function(x, theta, mu, s) {
    .Call(`_glam3_glam_scorefuncmu1`, x, theta, mu, s)
}

rcpp_hello_world <- function() {
    .Call(`_glam3_rcpp_hello_world`)
}

